title: People in space
hero_image: images/banner.png
description: Build an indicator of the number of people in space
original_url: https://www.raspberrypi.org/learning/people-in-space-indicator/
theme: cc-prototype
duration: 2
listed: false
published: false
ingredient: false
interests: space
technologies: python
steps:
  - title: Introduction
  - title: What you will need
  - title: The People in Space API
  - title: Examining the data
  - title: Setting up the LEDs
  - title: Testing your LEDs
  - title: An LED for each astronaut
  - title: What next?  
