---
title: People in space
hero_image: images/banner.png
description: Build an indicator of the number of people in outer space
original_url: https://www.raspberrypi.org/learning/people-in-space-indicator/
theme: cc-prototype
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
duration: 2
listed: true
published: false
ingredient: false
interests: space
technologies: python
hardware: ''
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: The People in Space API
- title: Examine the data
  completion:
  - engaged
- title: Set up the LEDs
- title: Control the LEDs with code
- title: An LED for each astronaut
  completion:
  - internal
- title: Challenge
  completion:
  - external
